[server]
defaultWorld = "world"
heartbeat = true
heartbeatURL = "http://www.classicube.net/server/heartbeat/"
host = "0.0.0.0"
levelName = "default"
maxPlayers = 20
motd = "Welcome!"
port = 20000
public = true
serverName = "Selenic Server"
useRelativeMovement = false
verifyNames = true
localBypassVerification = true