[server]
defaultWorld = "world"
heartbeatURL = "https://classicube.net/server/heartbeat"
host = "0.0.0.0"
maxPlayers = 20
motd = "Welcome!"
port = 20000
public = true
serverName = "Selenic Server"
verifyNames = true