[server]
defaultWorld = "world"
heartbeatURL = "http://www.classicube.net/server/heartbeat/"
host = "0.0.0.0"
levelName = "default"
maxPlayers = 20
motd = "Welcome!"
port = 25565
public = true
serverName = "Selenic Server"
useRelativeMovement = false
verifyNames = true